name: Simple HTML CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код из GitHub
        uses: actions/checkout@v3

      - name: Установка зависимостей
        run: npm install

      - name: Проверка на наличие index.html
        run: |
          if [ -f index.html ]; then
            echo "✅ Файл найден"
          else
            echo "❌ Файл не найден"
            exit 1
          fi

      - name: Проверка HTML через HTMLHint
        run: npx htmlhint
        
      - name: Проверка HTMLHint
        run: |
          echo "📂 Показать файлы"
          ls -la
          echo "🔎 Проверка HTMLHint"
          npx htmlhint index.html
